#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo ""
echo -e "\033[1;33mRunning pre-commit convention tests..\033[0m"
echo ""


if npx commitlint --edit ; then
  echo ""
  echo -e "\033[0;32m 🍀 All files are ready to push...\033[0m"
  echo ""
  exit 0
else
  echo ""
  echo -e "\033[0;31m ⌛️ There is some typo in commit message as above...\033[0m"
  echo ""
  echo -e "\033[0;31m 🚫 Please use one of this :- feat:/fix:/docs:/chore:  \033[0m"
  echo ""
  exit 1
fi