#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo ""
echo -e "\033[1;33mRunning formatting & lint tests on staged files..\033[0m"
echo ""

if npm run pre-commit; then
  echo ""
  echo '\033[0;32m🎉 No error found: committing this now.... ✨🚀🏄‍♂️🍻\033[0m'
  echo ""
  exit 0
else
  echo ""
  echo "\033[0;31m 🤔 Linting Error.Please fix the issues before committing.\033[0m"
  echo ""
  exit 1
fi